### ISSUE TITLE
Устаревший туториал

### ISSUE THREAD

**Issue by OferistKA** [TonSharp/WAPITIS#15]
https://github.com/TonSharp/WAPITIS/wiki/Tutorials#Готовый-код-1

![изображение_2021-09-24_000816](https://user-images.githubusercontent.com/79284753/134584243-f241ec38-64f8-4425-99f4-3f18e04ce82c.png)
Вместо list->Create(BORDER | **_VSCROLL_**, { 10, 140 }, { 270, 120 }); пишем **_NULL_**, а под ним list->AddVScroll()
Вместо **SelectElement** необходимо **SelectItem**

https://github.com/TonSharp/WAPITIS/wiki/Tutorials#Готовый-код-2
![image](https://user-images.githubusercontent.com/79284753/134585614-01618c1b-b313-49b8-97a4-f140d39eda77.png)
В строчке "list = new ListBox(L"", *wnd, args.hInstance, false);" убрать указатель на wnd

**Comment by TonSharp** [comment]
Спасибо за подробный отчет об устаревшей документации. Наши специалисты займутся решением данной проблемы в ближайшее время.
