### ISSUE TITLE
UI Tutorial

### ISSUE THREAD

**Issue by Reestry** [TonSharp/WAPITIS#7]
list->Create(BORDER | VSCROLL, { 10, 140 }, { 270, 120 });

Ошибка: идентификатор "VSCROLL" не определен

**Comment by TonSharp** [comment]
Для добавления вертикальной полосы прокрутки, вместо стиля VSCROLL, после создания списка используйте функцию:
`list->AddVScroll();`

Таким образом вы получите следующий код:
```c++
list->Create(BORDER, {10, 140}, {270, 120});
list->AddVScroll();
```
