### ISSUE TITLE
UI tutorial

### ISSUE THREAD

**Issue by Reestry** [TonSharp/WAPITIS#8]
list->AddElement(FirstList->GetSelectedString());

Ошибка: class "ComboBox" не содержит члена "GetSelectedString"

**Comment by TonSharp** [comment]
На данный момент WAPITIS не поддерживает функцию `GetSelectedString()` в ComboBox. В ближайшее время данная возможность будет добавлена.

Временное решение:
```c++
list->AddElement(FirstList->GetStringByIndex(FirstList->GetSelectedIndex()))

**Comment by TonSharp** [comment]
`ListBox` и `ComboBox` содержат методы `GetSelectedText`, которые позволяют получить текущую выбранную строку.

Пример:
```c++
list->GetSelectedText();
```
